username: tcoops
baseurl: /blog/
markdown: redcarpet
safe: false
highlighter: pygments
title: tcOops
description:  Geek,  SJTU|CS|Master,  C++|Python|C#,                BigData|Function Programming|Algorithm
theme: midnight
disqusname: minixalpha

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine
# those themes are all come from GitHub Pages Themes
