username: CAPOUIS
baseurl: /blog
markdown: redcarpet
safe: false
highlighter: pygments
title: CAPOUIS
description: Good guys do win!
theme: slate
disqusname: CAPOUIS

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine
# those themes are all come from GitHub Pages Themes
